

baseurl = "/home"
languageCode = "en-us"
title = "DreamForce 2016"
PygmentsCodeFences=true
pygmentsStyle="friendly"   

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/home"

[[menu.main]]
    name = "WORKSHOPS"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "workshop"
    url = "/workshop/"

[[menu.main]]

    name = "  Suggestion Box"
    pre = "<i class=''></i>"
    weight = 2
    identifier = "Suggestion Box"
    url = "/workshop/suggestion-box"

[[menu.main]]

    name = "  Battle Station"
    pre = "<i class=''></i>"
    weight = 3
    identifier = "battle station"
    url = "/workshop/battle-station"

[[menu.main]]

    name = "  Heroku Connect"
    pre = "<i class=''></i>"
    weight = 4
    identifier = "Heroku Connect"
    url = "/workshop/heroku-connect"


[[menu.main]]

    name = "  Prediction IO"
    pre = "<i class=''></i>"
    weight = 5
    identifier = "Prediction IO"
    url = "/workshop/prediction-io"


[[menu.main]]
    name = "MINIHACKS"
    pre = "<i class='fa fa-list fa-fw'></i>"
    identifier = "minihacks"
    weight = 8
    url = "/minihacks/"
