baseurl = "http://www.sfdcworkshop.com/"
languageCode = "en-us"
title = "Salesforce Developers 2016"
PygmentsCodeFences=true
pygmentsStyle="friendly"
googleAnalytics="UA-84811307-1"

[params]
  # Shown in the home page
  brand = "<div><img src='/workshop/2015sf_Developers_logo_RGB_KO.png' height='70'></div>"

[[menu.main]]
    name = "WORKSHOPS"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "workshop"
    url = "/workshop"

[[menu.main]]

    name = "  Lightning : Suggestion Box"
    pre = "<i class=''></i>"
    weight = 2
    identifier = "Suggestion Box"
    url = "/workshop/suggestion-box"

[[menu.main]]

    name = "  Lightning : Battle Station"
    pre = "<i class=''></i>"
    weight = 3
    identifier = "battle station"
    url = "/workshop/battle-station"

[[menu.main]]

    name = "  Heroku Connect"
    pre = "<i class=''></i>"
    weight = 4
    identifier = "Heroku Connect"
    url = "/workshop/heroku-connect"

[[menu.main]]

    name = "  PredictionIO"
    pre = "<i class=''></i>"
    weight = 5
    identifier = "PredictionIO"
    url = "/workshop/prediction-io"

[[menu.main]]

    name = "  Secure Apps"
    pre = "<i class=''></i>"
    weight = 6
    identifier = "Secure Apps"
    url = "/workshop/secure-apps"

