baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "DreamForce 2016 Workshops"
PygmentsCodeFences=true
pygmentsStyle="friendly"            

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/workshop/"

[[menu.main]]

    name = "Suggestion Box"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "Suggestion Box"
    url = "/workshop/suggestion-box"

[[menu.main]]

    name = "Conference Management"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "conference management"
    url = "/workshop/conference-mgmt"

[[menu.main]]

    name = "Heroku Connect"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "Heroku Connect"
    url = "/workshop/pythonapp"


[[menu.main]]

    name = "Wave APIs"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "Wave APIs"
    url = "/workshop/wave-apis"